title:              "비잉구루"
tagline:            "사람을 마케팅하다"
email:              "smyang1013@gmail.com"
description:        "구루(Guru)로 성장하는 마케터의 이야기"
author:             "비잉구루"
baseurl:            "/"
url:                "https://beingguru.life"
locale:             "ko_KR"
thumbnail:          "/img/thumbnail.jpg"

# Social Profiles
twitter_username:   twitter_username
instagram_username: instagram_username
facebook_username:  facebook_username
linkedin_username:  linkedin_username

# Build settings
markdown:           kramdown
permalink:          /:title
paginate:           5
paginate_path:      "/posts/page:num/"
highlighter:        rouge # 11.13 추가
plugins:
  - jekyll-paginate

# 블로그 disqus shortname
disqus:
  shortname: beingguru-1
